version: "3.8"
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.90.1
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
    networks:
      - otel-network
    environment:
      - CLICKHOUSE_ENDPOINT=${CLICKHOUSE_ENDPOINT}
      - CLICKHOUSE_DATABASE=${CLICKHOUSE_DATABASE}
      - CLICKHOUSE_USERNAME=${CLICKHOUSE_USERNAME}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}

  user-service:
    build: ../apps/user-service
    ports:
      - "4001:4001"
    networks:
      - otel-network
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317

  order-service:
    build: ../apps/order-service
    ports:
      - "4002:4002"
    networks:
      - otel-network
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317

  product-service:
    build: ../apps/product-service
    ports:
      - "4003:4003"
    networks:
      - otel-network
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317

networks:
  otel-network:
    driver: bridge
