version: "3.8"

services:
  otel-collector:
    build:
      context: ./otel-collector
      dockerfile: Dockerfile
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
    networks:
      - otel-network

networks:
  otel-network:
    driver: bridge
