receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  logging:
    loglevel: debug
  clickhouse:
    endpoint: "${CLICKHOUSE_ENDPOINT}"
    database: "${CLICKHOUSE_DATABASE}"
    username: "${CLICKHOUSE_USERNAME}"
    password: "${CLICKHOUSE_PASSWORD}"
    timeout: 10s
    sending_queue:
      queue_size: 100
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, clickhouse]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, clickhouse]